#SshOptionsDialog
const SSH_OPTIONS_DIALOG_NO_ERROR_LENGTH: int = 250
const SSH_OPTIONS_DIALOG_MAX_LENGTH: int = 400
const SSH_OPTIONS_DIALOG_LINE_CHARS: float = 27.0
const SSH_OPTIONS_DIALOG_LINE_HEIGHT: int = 30